config/routes.rb
Rails.application.routes.draw do
  root    'pages#home', as: :root

  get     'signup'    => 'users#new', as: :signup

  get     'login'  => 'logins#new', as: :login
  post    'login'  => 'logins#create', as: :login_create
  get     'logout' => 'logins#destroy', as: :logout

  get     'start'  => 'journeys#new', as: :journey_new
  post    'start'  => 'journeys#create', as: :journey_create

  post    'receive_sms'   => 'reports#create_from_sms'
  mount_griddler

  resources :users, only: [:new, :create, :edit, :update, :show] do
    member do
      get :confirm_email
    end
    resources :journeys, only: [:new, :create, :show] do
      resources :reports, only: [:new, :create, :update]
    end
  end
  resources :phone_verifications, only: [:new, :create]
end

app/views/user_notifier/registration_confirmation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Hello, <%= @user.name %>!</h3>
    <p>Thanks for joining. I hope you enjoy my habit development app.</p>

    <p>To confirm your registration click the URL below.</p>
    
    <p><%= confirm_email_user_url(@user.confirm_token) %></p>
  </body>
</html>

app/views/user_notifier/reminder_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    -- Reply ABOVE THIS LINE --
    <h3>Hey <%= @user.name %>,</h3>
    <p>We are waiting for your report. Don't break the image-chain!</p>
    <h4>To email a report: </h4>
    <p>Reply with a number from 1 to 10 and attach a picture.</p>
    <h4>To upload online:</h4>
    <p>
      click <%= link_to 'here', new_user_journey_report_url(@user, @user.current_journey) %>.
    </p>
  </body>
</html>

app/views/user_notifier/send_signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>