config/routes.rb
Rails.application.routes.draw do
  root    'pages#home', as: :root

  get     'signup'    => 'users#new', as: :signup

  get     'login'  => 'logins#new', as: :login
  post    'login'  => 'logins#create', as: :login_create
  get     'logout' => 'logins#destroy', as: :logout

  get     'start'  => 'journeys#new', as: :journey_new
  post    'start'  => 'journeys#create', as: :journey_create

  post    'receive_sms'   => 'reports#create_from_sms'
  mount_griddler

  resources :users, only: [:new, :create, :edit, :update, :show] do
    member do
      get :confirm_email
    end
    resources :journeys, only: [:new, :create, :show] do
      resources :reports, only: [:new, :create, :update]
    end
  end
  resources :phone_verifications, only: [:new, :create]
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p>
      test
    </p>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("confidence.svg"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Logout", logout_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= user_path(current_user) %>">Show</a></li>
              <li><%= link_to "Edit", edit_user_path(current_user) %></li>
              <% if current_user.has_current_journey? %>
                <li><%= link_to "Current Journey",
                  user_journey_path(current_user, active_journey) %>
              <% end %>
              </li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_lightbox.erb
  <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
  <div id="blueimp-gallery" class="blueimp-gallery">
      <!-- The container for the modal slides -->
      <div class="slides"></div>
      <!-- Controls for the borderless lightbox -->
      <h3 class="title"></h3>
      <a class="prev">‹</a>
      <a class="next">›</a>
      <a class="close">×</a>
      <a class="play-pause"></a>
      <ol class="indicator"></ol>
      <!-- The modal dialog, which will be used to wrap the lightbox content -->
      <div class="modal fade">
          <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" aria-hidden="true">&times;</button>
                      <h4 class="modal-title"></h4>
                  </div>
                  <div class="modal-body next"></div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default pull-left prev">
                          <i class="glyphicon glyphicon-chevron-left"></i>
                          Previous
                      </button>
                      <button type="button" class="btn btn-primary next">
                          Next
                          <i class="glyphicon glyphicon-chevron-right"></i>
                      </button>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
  <div id="blueimp-gallery" class="blueimp-gallery">
      <div class="slides"></div>
      <h3 class="title"></h3>
      <a class="prev">‹</a>
      <a class="next">›</a>
      <a class="close">×</a>
      <a class="play-pause"></a>
      <ol class="indicator"></ol>
  </div>

  <script>
  document.getElementById('links').onclick = function (event) {
      event = event || window.event;
      var target = event.target || event.srcElement,
          link = target.src ? target.parentNode : target,
          options = {index: link, event: event},
          links = this.getElementsByTagName('a');
      blueimp.Gallery(links, options);
  };
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASAPP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <% if params[:action] == 'home' %>
    <%= render 'pages/hero' %>
  <% end %>

  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>